/*
* EvoLauncher.h
*
*  Created on: Sep 20, 2017
*      Author: jjpalacios
*/
#pragma once

#include "MemeticNeri.h"
#include "ArtificialBeeColony.h"
#include "ArtificialBeeColonyThread.h"
#include "ArtificialBeeColonyPSO.h"
#include "ArtificialBeeColonyCell.h"
#include "RandomPopulation.h"
#include "PostExecutionManager.h"


namespace FuzzyFW {

	// Parameters defined in this header file
#define EVO_SEED "seed"	// Seed for the RNG
#define EVO_ALGORITHM "algorithm"	// Algorithm to use as optimisation method
#define EVO_RUNS "runs"				// Number of runs for algorithm
#define EVO_TEST_MODE "testMode"   // label for the test mode

// Name for sets of solutions
#define EVO_OUTPUT_SOLS "Sols"



	//=============================================================================
	//
	//	Class EvoLauncher
	//
	//=============================================================================
	/**
	* This is the entry point to use Evolutive algorithms.
	*
	* This class needs a configuration file containing all the parameters that the
	* algorithm needs to work.
	*
	* It will generate an output file with all the data generated by the solving
	* method and statistic values about it.
	*
	* @author jjpalacios
	*
	*/

	class EvoLauncher {
		//=========================================================================
		//		FIELDS
		//=========================================================================
	public:
		/**
		* Path to the folder in which store the results
		*/
		std::string logFolder;

		/**
		* Number of repetitions
		*/
		int numRuns;


	private:
		/**
		* Algorithm to use for calibration
		*/
		EvolutiveAlgorithm *algorithm;

		/**
		* Problem to solve
		*/
		Problem *problem;

		/**
		* Setup parameters for the algorithm
		*/
		ParameterDB *setup;
		
		/**
		* Seed for the Random Numbers Generator
		*/
		int seed;

		/**
		* flag for the test mode
		*/
		bool testMode;

		PostExecution::PostExecutionManager analyzer;

		/**
		* Private statistics obtained from the algorithm
		*/
		std::vector< std::vector< std::pair<std::string, double> > > avgTimes;
		std::vector< std::vector< std::pair<std::string, double> > > avgStats;
		std::vector< std::vector< std::vector<double> > > avgEvolStats;
		std::vector< std::string > avgEvolLabels;
		std::vector<Fitness *> fitnessValues;



		//=========================================================================
		//		CONSTRUCTORS / INITIALIZERS
		//=========================================================================
	public:
		/**
		* Main constructor. It requires the setup file for the algorithm
		*/
		EvoLauncher(const char* algorithmSetup);

		/**
		* Destructor
		*/
		~EvoLauncher();



		//=========================================================================
		//		MAIN METHODS
		//=========================================================================
	public:
		/**
		* This is the main method. It runs the algorithm and generates all the
		* output files
		*
		* @return The best solution found among all the runs
		*/
		std::string optimise(Problem *problem);

		/**
		* Method used to specify if the eecution is set in test mode
		*
		* @return true if the algorthm is in test mode
		*/
		bool isInTestMode();


		//=========================================================================
		//		CONFIGURATION METHODS
		//=========================================================================
	public:
		void setLogFolder(const char *path);


	private:
		/**
		* Load the configuration for the algorithm that is to be used for the
		* calibration process
		*
		* @param setupFile Path to the algorithm configuration file
		*/
		void loadConfiguration(const char* paramsFile);

		/**
		* Load the configuration for the algorithm that is to be used for the
		* calibration process
		*
		* @param name Name of the algorithm to use for calibration
		* @param setupFile Path to the algorithm configuration file
		*/
		void setupAlgorithm(const std::string name);


		/**
		* Generates a signature based on the current time
		*
		* @return a string format current date
		*/
		std::string generateSignature() const;



		//=========================================================================
		//		LOG
		//=========================================================================
		/**
		* Print the data about runtimes provided by the algorithm
		*
		* @param outputFile File in which print the data
		* @param data set of data with the values to print, the strings
		* are the name of the field and the double is the value.
		*/
		void printRuntimes(std::ofstream &outputFile);

		/**
		* Print the basic statistics provided by the algorithm itself
		*
		* @param outputFile File in which print the data
		* @param data set of data eith the values to print, the strings
		* are the name of the field and the double is the value.
		*/
		void printStatistics(std::ofstream &outputFile);

		/**
		* Print the objective function values
		*
		* @param outputFile File in which print the data
		*/
		void printObjectiveValues(std::ofstream &outputFile);


		/**
		* Print the evolution of the algorithm provided by itself
		*
		* @param outputFile File in which print the data
		* @param data matrix with the data values to print
		* @param labels Labels for each column in the matrix data
		*/
		void printEvolutionTrace(std::ofstream &outputFile);

	};

}

